name: Regression

on:
  schedule: 
    - cron: '0 5 * * *' # every day at 07:00 UTC

  workflow_dispatch: # Run manually

jobs:
  regression:
    uses: SkylineCommunications/BOOST-DailyRegression/.github/workflows/regression.yml@main
    with:
      workflow-name: complete.yml
      job-number: 0
    secrets:
      msteams-webhook: ${{ secrets.TEAMS_WEBHOOK }}
  
  regression-oidc:
    needs: regression
    uses: SkylineCommunications/BOOST-DailyRegression/.github/workflows/regression.yml@main
    with:
      workflow-name: complete-oidc.yml
      job-number: 1
    secrets:
      msteams-webhook: ${{ secrets.TEAMS_WEBHOOK }}